const mongoose = require("mongoose");
const Schema = mongoose.Schema;


const registronSchema = new mongoose.Schema({
    dateTime: { type: Date, required: true },
    estadoAnimo: { type: String, required: true },
    professional: { type: Schema.ObjectId, ref: "user" },
    pacient: { type: Schema.ObjectId, ref: "user" },
    desayunoL: { type: String },
    mediaL: { type: String },
    almuerzoL: { type: String},
    meriendaL: { type: String},
    cenaL: { type: String},
    desayunoM: { type: String},
    mediaM: { type: String },
    almuerzoM: { type: String},
    meriendaM: { type: String},
    cenaM: { type: String},
    desayunoX: { type: String},
    mediaX: { type: String },
    almuerzoX: { type: String},
    meriendaX: { type: String},
    cenaX: { type: String},
    desayunoJ: { type: String},
    mediaJ: { type: String },
    almuerzoJ: { type: String},
    meriendaJ: { type: String},
    cenaJ: { type: String},
    desayunoV: { type: String },
    mediaV: { type: String },
    almuerzoV: { type: String},
    meriendaV: { type: String},
    cenaV: { type: String},
    desayunoS: { type: String},
    mediaS: { type: String },
    almuerzoS: { type: String},
    meriendaS: { type: String},
    cenaD: { type: String},
    desayunoD: { type: String },
    mediaD: { type: String },
    almuerzoD: { type: String},
    meriendaD: { type: String},
    cenaD: { type: String},
});
module.exports = Registron = mongoose.model("registron", registronSchema);