const mongoose = require("mongoose");
const Schema = mongoose.Schema;


const registronSchema = new mongoose.Schema({
    dateTime: { type: Date },
    estadoAnimo: { type: String },
    professional: { type: Schema.ObjectId, ref: "user" },
    pacient: { type: Schema.ObjectId, ref: "user" },
    desayunoL: { type: Schema.ObjectId, ref: "menu" },
    mediaL: { type: Schema.ObjectId, ref: "menu" },
    almuerzoL: { type: Schema.ObjectId, ref: "menu" },
    meriendaL: { type: Schema.ObjectId, ref: "menu" },
    cenaL: { type: Schema.ObjectId, ref: "menu" },
    desayunoM: { type: Schema.ObjectId, ref: "menu" },
    mediaM: { type: Schema.ObjectId, ref: "menu" },
    almuerzoM: { type: Schema.ObjectId, ref: "menu" },
    meriendaM: { type: Schema.ObjectId, ref: "menu" },
    cenaM: { type: Schema.ObjectId, ref: "menu" },
    desayunoX: { type: Schema.ObjectId, ref: "menu" },
    mediaX: { type: Schema.ObjectId, ref: "menu" },
    almuerzoX: { type: Schema.ObjectId, ref: "menu" },
    meriendaX: { type: Schema.ObjectId, ref: "menu" },
    cenaX: { type: Schema.ObjectId, ref: "menu" },
    desayunoJ: { type: Schema.ObjectId, ref: "menu" },
    mediaJ: { type: Schema.ObjectId, ref: "menu" },
    almuerzoJ: { type: Schema.ObjectId, ref: "menu" },
    meriendaJ: { type: Schema.ObjectId, ref: "menu" },
    cenaJ: { type: Schema.ObjectId, ref: "menu" },
    desayunoV: { type: Schema.ObjectId, ref: "menu" },
    mediaV: { type: Schema.ObjectId, ref: "menu" },
    almuerzoV: { type: Schema.ObjectId, ref: "menu" },
    meriendaV: { type: Schema.ObjectId, ref: "menu" },
    cenaV: { type: Schema.ObjectId, ref: "menu" },
    desayunoS: { type: Schema.ObjectId, ref: "menu" },
    mediaS: { type: Schema.ObjectId, ref: "menu" },
    almuerzoS: { type: Schema.ObjectId, ref: "menu" },
    meriendaS: { type: Schema.ObjectId, ref: "menu" },
    cenaS: { type: Schema.ObjectId, ref: "menu" },
    desayunoD: { type: Schema.ObjectId, ref: "menu" },
    mediaD: { type: Schema.ObjectId, ref: "menu" },
    almuerzoD: { type: Schema.ObjectId, ref: "menu" },
    meriendaD: { type: Schema.ObjectId, ref: "menu" },
    cenaD: { type: Schema.ObjectId, ref: "menu" },
});
module.exports = Registron = mongoose.model("registron", registronSchema);